# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx6g -XX:+UseG1GC -XX:MaxGCPauseMillis=200

# Serial execution (low memory)
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=false

kotlin.jvm.target.version=17
kotlin.compiler.freeArgs=-Xjvm-default=all -opt-in=kotlin.RequiresOptIn -opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi

android.useAndroidX=true
android.nonTransitiveRClass=true

android.injected.testOnly=false