name: Code Style

on:
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '.editorconfig'
      - 'gradle/libs.versions.toml'
  push:
    branches: [main]
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '.editorconfig'
      - 'gradle/libs.versions.toml'

permissions:
  contents: read

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: ktlintCheck
        run: ./gradlew :app:ktlintCheck --no-daemon
